//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostumerRegister
    {
        public int ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string TellNo { get; set; }
        public string Occupation { get; set; }
        public string Address1 { get; set; }
        public byte[] Picture { get; set; }
        public string DateRegistered { get; set; }
        public string Address2 { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> BookedRoomPrice { get; set; }
        public string NxtOfKinName { get; set; }
        public string NxtOfKinNumber { get; set; }
        public string NxtOfKinRelationship { get; set; }
    }
}
