//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCategoryType
    {
        public int RoomID { get; set; }
        public string RoomType { get; set; }
        public int Quantity { get; set; }
        public byte[] Picture { get; set; }
        public string ShortDescription { get; set; }
        public decimal Price { get; set; }
    }
}
